version: "3.0"

services:
  web_server:
    container_name: atp_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    volumes:
      - ".:/app"
    networks:
      deployments_bito_net:
        ipv4_address: 72.19.0.10

  redis:
    container_name: atp_redis
    restart: always
    # image: redis:6.2
    build:
      context: ./docker_files/redis/
      dockerfile: Dockerfile
    ports:
      - "6499:6379"
    networks:
      deployments_bito_net:
        ipv4_address: 72.19.0.100

  mysql:
    container_name: atp_redis
    restart: always
    # image: redis:6.2
    build:
      context: ./docker_files/redis/
      dockerfile: Dockerfile
    ports:
      - "6499:6379"
    networks:
      deployments_bito_net:
        ipv4_address: 72.19.0.100

networks:
  animation_web_net:
    external: true